---
global:
  blacklist:
    enabled: true
    id: 0WqRYEtkaDQs6cfPrOAPEr
archiver:
  - Not existing Playlist
  - Test
  - source: Test
    target: Test (object-config)
  - source:
      id: 1gkbBs6dbYLGA5HLwubHN7
    target: Test (by id)
  - source:
      name: Test (renamable)
      findByPersistence: true
    target: Test - Copy of renamed Playlist
